galaxy_info:
  description: Setup the operating system to function as a Container OS using Podman
  author: kriansa
  license: BSD
  min_ansible_version: 2.11

  platforms:
  - name: RedHat
    versions:
      - 9
  - name: Debian
    versions:
      - 12

  galaxy_tags:
    - containers

dependencies:
  - role: os_base
