---
- name: reboot
  become: true
  reboot:

- name: restart ssh
  become: true
  systemd: name=sshd state=restarted

- name: restart cloudwatch
  become: true
  service: name=amazon-cloudwatch-agent enabled=yes state=restarted
