---
- file: path=/var/run/yum.pid state=absent
  become: true

- name: upgrade all packages
  become: true
  yum:
    name: '*'
    state: latest
    update_cache: true
    exclude: kernel
    lock_timeout: 300

# - file: path=/var/run/yum.pid state=absent
#   become: true

- name: install utility packages
  become: true
  yum:
    name: "{{ packages }}"
    state: latest
    lock_timeout: 90
  vars:
    packages:
      - auter
      - htop

- file: path=/var/run/yum.pid state=absent
  become: true

- name: upgrade the kernel
  notify: reboot
  become: true
  yum: name=kernel state=latest lock_timeout=300
