---
- import_tasks: set_hostname.yml
- import_tasks: install_epel.yml
- import_tasks: install_packages.yml
- import_tasks: persist_journal.yml
- import_tasks: grub_tuning.yml
- import_tasks: security_hardening.yml
- import_tasks: install_cloudwatch_agent.yml
  when: install_cloudwatch == true and ansible_facts['distribution'] == 'Amazon'
