---
- name: enable auto-reboot after kernel upgrades
  become: true
  lineinfile:
    path: /etc/auter/auter.conf
    regexp: '^AUTOREBOOT='
    line: 'AUTOREBOOT="yes"'

- name: enable auto-updates to run after 2:30AM
  become: true
  blockinfile:
    path: /etc/cron.d/auter
    block: |
      # Enable auto updates every 2:30AM
      30 2 * * * root /usr/bin/auter --apply

- name: disable password SSH auth
  become: true
  notify: restart ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: PasswordAuthentication no

- name: gather installed packages facts
  become: true
  package_facts:
    manager: rpm

- name: open ports on firewalld
  become: true
  when: ansible_distribution == 'CentOS' and open_ports|length > 0 and 'firewalld' in ansible_facts.packages
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ open_ports }}"
