---
- import_tasks: configure_debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- import_tasks: configure_rhel.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: add wg-reresolve-dns bin
  become: true
  notify: restart wg-reresolve-dns
  ansible.builtin.copy:
    src: wg-reresolve-dns
    mode: "0755"
    dest: /usr/local/bin/

- name: add wireguard reresolver systemd unit
  become: true
  notify:
    - reload systemd daemon
    - restart wg-reresolve-dns
  ansible.builtin.copy:
    src: wg-reresolve-dns.service
    dest: /etc/systemd/system/

- name: enable wireguard reresolver
  become: true
  ansible.builtin.systemd:
    name: wg-reresolve-dns.service
    enabled: yes
    state: started
    daemon_reload: yes

- name: Enable SSH through VPN only
  become: true
  when: ssh_only_through_vpn
  block:
    - name: Set ssh daemon listener to the VPN IP
      notify: restart ssh
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        insertafter: '^#ListenAddress ::'
        line: "ListenAddress {{ vpn_ip }}"

    - name: Create ssh service drop-in directory
      ansible.builtin.file: state=directory mode=0755 path=/etc/systemd/system/sshd.service.d

    - name: Add ssh drop-in to wait for wg to come up before starting up
      notify: reload systemd daemon
      ansible.builtin.copy:
        dest: /etc/systemd/system/sshd.service.d/10-wait-wg.conf
        mode: 0644
        content: |
          [Unit]
          After=network.target systemd-networkd.service
          Requires=sys-devices-virtual-net-vpn.device
