---
# Sets the hostname of this server
hostname: myserver

# Admin user name. By default, we disable root user and turn this one into an admin which can get
# super user access by using `doas`
username: admin

# The URL to fetch the authorized_keys from (typically https://github.com/<your_username>.keys)
authorized_keys_url: ""

# Should we remove firewalld? Set to yes if you use on a cloud provider that already provides
# firewall functionality
remove_firewalld: yes

# Install CloudWatch agent on Amazon Linux?
install_cloudwatch: yes

# Remove OS bloat packages?
remove_bloat: yes

# Should we update the kernel when this playbook run? That requires a reboot
update_kernel: yes

# Automatic updates
# -----------------

# Should we configure the automatic updates?
automatic_update_download_time: 02:00
automatic_update_reboot: yes

# The options below are only applicable to Debian
# -----------------------------------------------

automatic_update_start_time: 02:30
automatic_update_email_report: ""

# When automatic updates are on, should we update the kernel as well? Those always require a reboot
automatic_update_kernel: yes

# When should we reboot after a update that requires it?
automatic_update_reboot_time: 03:00
