---
# Sets the hostname of this server
hostname: myserver

# Admin user name. By default, we disable root user and turn this one into an admin which can get
# super user access by using `sudo`
username: admin

# The URL to fetch the authorized_keys from (typically https://github.com/<your_username>.keys)
authorized_keys_url: ""

# Should we remove firewalld? Set to yes if you use on a cloud provider that already provides
# firewall functionality
remove_firewalld: yes

# Debian 12 introduces netplan to manage its systemd-networkd configuration. Should we remove it?
remove_netplan: yes

# Install CloudWatch agent on Amazon Linux
install_cloudwatch: yes

# Should we install SSHGuard for public-facing SSH servers?
install_sshguard: no

# Remove OS bloat packages not required for servers
remove_bloat: yes

# Should we reboot after the playbook has run if required
reboot_if_needed: yes

# Automatic updates (timezones available at `timedatectl list-timezones`)
automatic_update_enabled: yes
automatic_update_download_time: 02:00 UTC
automatic_update_start_time: 02:30 UTC
automatic_update_reboot: yes
automatic_update_reboot_time: 03:00 UTC
