---
# Sets the hostname of this server
hostname: myserver

# Specify if you want to open ports for this server.
# The format is the following:
# - 80/tcp
open_ports: []

# Install CloudWatch agent?
install_cloudwatch: yes

# Should we update the kernel? That needs a reboot.
update_kernel: yes
