---
- name: install wireguard-tools
  become: true
  ansible.builtin.dnf: name=wireguard-tools

- name: setup vpn interface
  become: true
  notify: restart ssh
  ansible.builtin.template:
    src: files/VPN.nmconnection
    mode: "0600"
    dest: /etc/NetworkManager/system-connections/VPN.nmconnection

- name: restart NetworkManager to activate vpn
  become: true
  ansible.builtin.systemd: name=NetworkManager state=restarted
