---
- name: install wireguard-tools
  become: true
  ansible.builtin.dnf: name=wireguard-tools

- name: setup vpn interface
  become: true
  notify: restart ssh
  ansible.builtin.template:
    src: files/VPN.nmconnection
    mode: "0600"
    dest: /etc/NetworkManager/system-connections/VPN.nmconnection

- name: restart NetworkManager to activate vpn
  become: true
  ansible.builtin.systemd: name=NetworkManager state=restarted

- name: create ssh service drop-in directory
  become: true
  ansible.builtin.file: state=directory path=/etc/systemd/system/sshd.service.d

- name: add ssh drop-in to wait for wg to come up before starting up
  become: true
  notify: reload systemd daemon
  ansible.builtin.copy:
    dest: /etc/systemd/system/sshd.service.d/10-wait-wg.conf
    content: |
      [Unit]
      After=network.target NetworkManager.service
      Requires=sys-devices-virtual-net-vpn.device
