---
# Undo most of the actions done by AlmaLinux cloud-image setup, whenever they aren't unsuited for a
# container host.
#
# See: https://github.com/AlmaLinux/cloud-images/blob/master/ansible/roles/gencloud_guest/tasks/main.yml

- name: install linux-firmware on bare metal hosts
  when: ansible_facts.virtualization_role == "host"
  become: true
  ansible.builtin.dnf:
    name: linux-firmware

- name: remove additional software
  become: true
  ansible.builtin.dnf:
    state: absent
    name:
      - cockpit
      - cockpit-*
      - nfs-utils
      - rsync
      - tar
      - tuned

- name: enable predictable network interface names
  become: true
  block:
    - ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/udev/rules.d/80-net-setup-link.rules

    - ansible.builtin.command: grep -q "net.ifnames" /proc/cmdline
      ignore_errors: true
      register: has_ifnames

    - notify: reboot
      when: has_ifnames.rc == 0
      ansible.builtin.command: grubby --update-kernel=ALL --remove-args="biosdevname net.ifnames"

# Remove xen support
- name: remove xen support
  become: true
  register: xen_removal
  ansible.builtin.file:
    path: /etc/dracut.conf.d/xen.conf
    state: absent

- name: regenerate the initramfs
  when: xen_removal.changed
  become: true
  command: dracut -f --regenerate-all

- name: remove almalinux user from /etc/sudoers
  become: true
  ansible.builtin.lineinfile:
    state: absent
    path: /etc/sudoers
    regexp: '^almalinux'

# Remove qemu-guest-agent for non-QEMU systems
- name: remove qemu-guest-agent
  when: ansible_facts.chassis_vendor != "QEMU"
  become: true
  ansible.builtin.dnf:
    state: absent
    name: qemu-guest-agent
