# Status: Disabled
---
- name: install tuned
  become: true
  ansible.builtin.package: state=latest name=tuned

- name: set tuned profile to throughput-performance
  become: true
  ansible.builtin.command: tuned-adm profile throughput-performance

- name: disable daemon mode for tuned
  become: true
  notify: restart tuned
  ansible.builtin.lineinfile:
    path: /etc/tuned/tuned-main.conf
    regexp: '^daemon ='
    line: "daemon = 0"

- name: shutdown polkit
  become: true
  ansible.builtin.systemd:
    state: stopped
    name: "{{ item }}"
  loop: [tuned, polkit]
