---
- set_fact:
    epel_version: "{{ ansible_facts['distribution_major_version'] }}"

- name: add epel GPG key
  become: true
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ epel_version }}

- name: install epel
  become: true
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ epel_version }}.noarch.rpm"
    state: latest
