---
- set_fact:
    epel_version: "{{ ansible_facts['distribution_major_version'] if ansible_facts['distribution'] == 'CentOS' else '7' }}"
    need_yum_priorities: "{{ ansible_facts['distribution'] != 'CentOS' }}"

- name: add epel GPG key
  become: true
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ epel_version }}

- name: install epel
  become: true
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ epel_version }}.noarch.rpm"
    state: latest

- name: install yum-plugin-priorities
  become: true
  when: need_yum_priorities == True
  yum: name=yum-plugin-priorities state=latest

- name: ensure that epel doesn't obsolete system packages
  become: true
  when: need_yum_priorities == True
  lineinfile:
    path: /etc/yum/pluginconf.d/priorities.conf
    line: check_obsoletes = 1
