---
- name: install auter
  become: true
  ansible.builtin.dnf: name=auter state=latest

- name: enable auto-reboot after kernel upgrades
  become: true
  when: automatic_update_reboot == true
  ansible.builtin.lineinfile:
    path: /etc/auter/auter.conf
    regexp: '^AUTOREBOOT='
    line: 'AUTOREBOOT="yes"'

- name: install auter systemd timers
  become: true
  ansible.builtin.template: src={{ item.src }} dest=/etc/systemd/system/{{ item.dest }}
  with_items:
    - { src: files/auter.service, dest: auter.service }
    - { src: files/auter.timer.j2, dest: auter.timer }
  notify:
    - reload systemd daemon

- name: enable auter schedule
  become: true
  ansible.builtin.systemd: name={{ item }} enabled=yes daemon_reload=yes
  with_items:
    - auter.service
    - auter.timer
