---
- name: remove software unsuited for general-purpose servers
  when: remove_bloat
  become: true
  ansible.builtin.dnf: name={{ packages }} state=absent
  vars:
    packages:
      - cockpit
      - cockpit-*
      - python2
      - python2-libs
      - python2-pip
      - python2-pip-wheel
      - python2-setuptools
      - python2-setuptools-wheel
      - emacs-filesystem
      - mysql-release-el8
      - mesa-*
      - adobe-source-code-pro-fonts
      - PackageKit
      - gssproxy
      - rpcbind
      - webkit2gtk3-jsc
      - sssd-client
      - sssd-common
      - sssd-kcm
      - sssd-nfs-idmap
      - slang
      - tuned

- name: remove firewalld
  when: remove_firewalld
  become: true
  ansible.builtin.dnf: name=firewalld* state=absent

- name: upgrade all packages
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true

- name: check if a reboot is required
  ansible.builtin.shell: dnf needs-restarting --reboothint
  failed_when: False
  register: reboot_required
  changed_when: reboot_required.rc != 0
  notify: reboot
