---
- name: use debian CDN and enable non-free repo
  become: true
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list

- name: update apt
  become: true
  ansible.builtin.apt:
    update_cache: yes
