---
- name: install unattended-upgrades package
  become: true
  ansible.builtin.apt: name=unattended-upgrades

- name: configure automatic upgrades
  become: true
  ansible.builtin.template:
    src: files/automatic-upgrades.j2
    dest: /etc/apt/apt.conf.d/90automatic-upgrades

- name: create folders for applying timer overrides
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/{{ item }}.timer.d
    state: directory
  loop:
    - apt-daily
    - apt-daily-upgrade

- name: override timers
  become: true
  ansible.builtin.template:
    src: files/{{ item }}.timer.j2
    dest: /etc/systemd/system/{{ item }}.timer.d/override.conf
  loop:
    - apt-daily
    - apt-daily-upgrade

- name: force reload the systemd daemon
  become: true
  ansible.builtin.systemd: daemon_reload=yes

- name: configure automatic updates
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}.timer"
    enabled: "{{ automatic_update_enabled }}"
  loop:
    - apt-daily
    - apt-daily-upgrade
